//used in burgerBuilder actions and reducer
export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENT='SET_INGREDIENT';
export const FETCH_INGREDIENT_FAILED='FETCH_INGREDIENT_FAILED';

//used in order actions and reducer
export const PURCHASE_INIT='PURCHASE_INIT';
export const PURCHASE_BURGER_START='PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL';

export const FETCH_ORDRERS_START='FETCH_ORDRERS_START';
export const FETCH_ORDRERS_SUCCESS='FETCH_ORDRERS_SUCCESS';
export const FETCH_ORDRERS_FAIL='FETCH_ORDRERS_FAIL';

//used in auth actions and reducer
export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';